version: '3.1'
services:
  python:
    build: ./
    command: python3 ./main.py

  database:
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devops

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080